name: pyjs-wasm
channels:
  - conda-forge
dependencies:
  - cmake
  - pip
  - python
  - yarn
  - click
  - empack >=3.0.1
  - microsoft::playwright
  - ninja
  - nodejs
  - pyjs_code_runner >= 2.0.1
  - exceptiongroup
  # documentation
  - jupytext
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
  - empack >=3.2.0
  - jupyter_server  # to enable contents
  - jupyterlite
  - jupyterlite-xeus
  - jupyterlite-sphinx
  - notebook >=7,<8  # to include the extension to switch between JupyterLab and Notebook
  # pyjs_code_runner dev deps
  - hatchling
  - emscripten_emscripten-wasm32 == 3.1.58
  - pip:
    - JLDracula
    - pyjs_code_runner >= 3.0
